### PR TITLE
Add UI Styles in Quiz page #12

### PR DESCRIPTION
**Pull request by rohitdubey1352**
Add UI Styles in Quiz page  #12 
Issue No: - #12 
Kindly accept the PR and make the Hacktoberfest Accept.
Also, Labeled with Hacktoberfest

### CODE REVIEW

**Comment by bhaavvya** [comment]
Already done.

**Comment by rohitdubey1352** [comment]
> Already done.

Hey, @bhaavvya I have seen the current design and I don't think its a good user interface.
And Have you seen mine design.
This one is home page
Screenshot (215)

And this is for Quiz:
Screenshot (217)

Can I have still chance to get the accept badge?

**Comment by bhaavvya** [comment]
Resolve conflicts.

**Comment by rohitdubey1352** [comment]
I think i had some mistake, what should i do?

**Pull request closed without merging**
