### PR TITLE
Negative and less Score bug fix

### PR DESCRIPTION
**Pull request by mangalgithub**

### CODE REVIEW

**Comment by bhaavvya** [comment]
Resolve conflicts

**Comment by mangalgithub** [comment]
how to resolve conflicts. 
pls help.

**Comment by mangalgithub** [comment]
Resolved conflict

**Comment by mangalgithub** [comment]
If anything else pls let me know.

**Comment by bhaavvya** [comment]
Okay don't worry. I will change settings and merge it.

**Comment by mangalgithub** [comment]
Thanks!

**Comment by mangalgithub** [comment]
Screenshot 2023-10-01 112508
Screenshot 2023-10-01 112516

The merged file for solving issue #17 has link which don't apply css

Screenshot 2023-10-01 112431
Screenshot 2023-10-01 112443

Is this issue causing merge conflict or only I am getting this in my local system
@bhaavvya

**Comment by mangalgithub** [comment]
same for script tag in index.html

**Comment by bhaavvya** [comment]
Do one thing i will close this pr and u delete the branch and repeat the steps using cmd.

**Pull request closed without merging**
