### PR TITLE
Fix/score

### PR DESCRIPTION
**Pull request by mangalgithub**
Fixed the negative score value or less score

### CODE REVIEW

**Comment by bhaavvya** [comment]
There is something wrong because others also have made pr and their was successful.

**Comment by mangalgithub** [comment]
Mam what is wrong can you tell.

**Comment by mangalgithub** [comment]
Solved the merge conflict

**Comment by bhaavvya** [comment]
Good work 👍

**Comment by mangalgithub** [comment]
Thanks mam for your support 👍

**Comment by bhaavvya** [comment]
It still gives negative score.

**Comment by mangalgithub** [comment]
Can you share the screenshot or tell me where it is showing negative score.

**Comment by mangalgithub** [comment]
image

 If  it is showing like this then this is due the original code where in the highscores section the score are shown like name - score
image

This hypen is looking like negative.
So, I also changed this in pr  #48

**Pull request merged**
