### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mangalgithub**

### CODE REVIEW

**Comment by bhaavvya** [comment]
Issue First then Pull Request and then this request will be merged. I f you have any query can ask here.All the best.

**Comment by rohitdubey1352** [comment]
So, basically we have to just add our details in Contributing.md only? For getting a successfully PR?

**Comment by bhaavvya** [comment]
Then update CONTRIBUTION.md

**Comment by rohitdubey1352** [comment]
Okay, Cool I got it

**Pull request closed without merging**
